In [8]:
import sklearn
import sklearn.ensemble
import numpy as np

In [13]:
dummy_test_data = np.array([
    [4.,7., 800.],
    [4.,8., 900.],
    [1.,4., 600.],
    [2.,3., 200.]
])
dummy_train_data = np.array([
    [5.,8., 1000.],
    [6.,9., 1050.],
])

[[   5.    8. 1000.]
 [   6.    9. 1050.]]


In [7]:
forest_model = sklearn.ensemble.RandomForestRegressor(
    n_estimators=100,
    criterion='squared_error', 
    max_depth=None, 
    min_samples_split=2, 
    min_samples_leaf=1, 
    min_weight_fraction_leaf=0.0, 
    max_features=1.0, 
    max_leaf_nodes=None, 
    min_impurity_decrease=0.0, 
    bootstrap=True, 
    oob_score=False, 
    n_jobs=None, 
    random_state=None, 
    verbose=0, 
    warm_start=False, 
    ccp_alpha=0.0, 
    max_samples=None
)

In [25]:
train_x = dummy_train_data[:,0:2]
train_y = (dummy_train_data[:, 2:]).flatten()
print(train_x.shape)
print(train_y)
test_x = dummy_test_data[:,0:2]
print(test_x)

(2, 2)
[1000. 1050.]
[[4. 7.]
 [4. 8.]
 [1. 4.]
 [2. 3.]]


In [20]:
forest_model.fit(train_x, train_y)

RandomForestRegressor()

In [26]:
test_preds = forest_model.predict(test_x)
test_preds

array([1011., 1011., 1011., 1011.])